/* Generated by Cython 0.29.24 */

#ifndef __PYX_HAVE__CVPuckYou
#define __PYX_HAVE__CVPuckYou

#include "Python.h"

#ifndef __PYX_HAVE_API__CVPuckYou

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void print_hello(void);
__PYX_EXTERN_C int getHeading(std::string const );
__PYX_EXTERN_C std::pair<int,int>  getPose(std::string const );
__PYX_EXTERN_C std::pair<int,int>  getDestination(std::string const , std::string const );
__PYX_EXTERN_C std::string getMap(std::string const );

#endif /* !__PYX_HAVE_API__CVPuckYou */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initCVPuckYou(void);
#else
PyMODINIT_FUNC PyInit_CVPuckYou(void);
#endif

#endif /* !__PYX_HAVE__CVPuckYou */
